remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: Tin Bo
#logo: 
description: This is my portfolio
#show_download:
theme: jekyll-theme-minimal
google_analytics: G-H58BSWDMR3
